[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://backend-citas-medicas.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://backend-citas-medicas.onrender.com/api"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  VITE_API_URL = "https://backend-citas-medicas.onrender.com/api"
